### ISSUE TITLE
Coq 8.5 feature guide

### ISSUE THREAD

**Issue by MarisaKirisame** [MarisaKirisame/MarisaKirisame.github.io#3]
A short introduction to show the benefit of 8.5 comparing to 8.4

**Comment by lolisa** [comment]
universe polymorphism
-type-in-type
Derive
Refine Instance Mode
backtracking tactic
tactic that apply to all goal
shelve_unifiable
dependent subgoal
give_up
tryif
dintuition
dtauto
Bullet suggestion when a subgoal is solved.
In destruct/induction, experimental modifier "!" prefixing the hypothesis name to tell not erasing the hypothesis.
Parallel proof
CoqIDE highlight(unsafe+more colorful)
CoqIDE autocomplete
asynchronous edition
